language: php

php:
  - 7.0

sudo: false

before_script:
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit